//red text for waitTime above 2hrs
export const isWaitTimeOverTwoHours = (waitTime) => {
  // This regular expression matches "超過" followed by one or more digits and then "小時"
  const overHoursRegex = /超過\s*(\d+)\s*小時/;
  const match = waitTime.match(overHoursRegex);

  if (match) {
    // Extract the number and convert it to an integer
    const hours = parseInt(match[1], 10);
    // Check if the extracted hours are greater than or equal to 2
    return hours >= 2;
  }

  return false;
};

export const hospitalSpecialistServices = [
  {
    name: "靈實醫院",
    type: "九龍東醫院聯網",
    contact: "2703 8888 / 2409 5868",
    website:
      "https://www.ha.org.hk/visitor/ha_visitor_index.asp?Content_ID=100157&Lang=CHIB5",
    address: "將軍澳靈實路8號",
    specialistServices: {
      內科: 1,
      外科: 0,
      心胸外科: 0,
      麻醉科: 0,
      臨床腫瘤科: 0,
      眼科: 0,
      耳鼻喉科: 0,
      神經外科: 0,
      精神科: 0,
      骨科: 0,
      紓緩醫學科: 1,
      婦科: 0,
      產科: 0,
      兒科: 0,
      牙科: 0,
    },
  },
  {
    name: "基督教聯合醫院",
    type: "九龍東醫院聯網",
    contact: "2379 9611",
    website:
      "https://www.ha.org.hk/visitor/ha_visitor_index.asp?Content_ID=100156&Lang=CHIB5",
    address: "九龍觀塘協和街130號",
    specialistServices: {
      內科: 1,
      外科: 1,
      心胸外科: 0,
      麻醉科: 1,
      臨床腫瘤科: 0,
      眼科: 1,
      耳鼻喉科: 0,
      神經外科: 1,
      精神科: 1,
      骨科: 1,
      紓緩醫學科: 1,
      婦科: 1,
      產科: 1,
      兒科: 1,
      牙科: 1,
    },
  },
  {
    name: "仁濟醫院",
    type: "九龍西醫院聯網",
    contact: "2417 8383",
    website:
      "https://www.ha.org.hk/visitor/ha_visitor_index.asp?Content_ID=100165&Lang=CHIB5",
    address: "新界荃灣仁濟街7-11號",
    specialistServices: {
      內科: 1,
      外科: 0,
      心胸外科: 0,
      麻醉科: 0,
      臨床腫瘤科: 0,
      眼科: 0,
      耳鼻喉科: 0,
      神經外科: 0,
      精神科: 0,
      骨科: 0,
      紓緩醫學科: 1,
      婦科: 0,
      產科: 0,
      兒科: 0,
      牙科: 0,
    },
  },
  {
    name: "將軍澳醫院",
    type: "九龍東醫院聯網",
    contact: "2208 0111",
    website:
      "https://www.ha.org.hk/visitor/ha_visitor_index.asp?Content_ID=101326&Lang=CHIB5",
    address: "將軍澳坑口寶寧里2號",
    specialistServices: {
      內科: 1,
      外科: 1,
      心胸外科: 0,
      麻醉科: 0,
      臨床腫瘤科: 0,
      眼科: 1,
      耳鼻喉科: 1,
      神經外科: 0,
      精神科: 1,
      骨科: 1,
      紓緩醫學科: 1,
      婦科: 1,
      產科: 1,
      兒科: 1,
      牙科: 0,
    },
  },
  {
    name: "東華醫院",
    type: "港島西醫院聯網",
    contact: "2589 8111",
    website:
      "https://www.ha.org.hk/visitor/ha_visitor_index.asp?Content_ID=100134&Lang=CHIB5",
    address: "香港上環普仁街12號",
    specialistServices: {
      內科: 1,
      外科: 1,
      心胸外科: 0,
      麻醉科: 0,
      臨床腫瘤科: 0,
      眼科: 0,
      耳鼻喉科: 1,
      神經外科: 0,
      精神科: 0,
      骨科: 0,
      紓緩醫學科: 0,
      婦科: 0,
      產科: 0,
      兒科: 0,
      牙科: 0,
    },
  },
  {
    name: "東華東院",
    type: "港島東醫院聯網",
    contact: "2162 6888",
    website:
      "https://www.ha.org.hk/visitor/ha_visitor_index.asp?Content_ID=100145&Lang=CHIB5",
    address: "香港銅鑼灣東院道19號",
    specialistServices: {
      內科: 1,
      外科: 0,
      心胸外科: 0,
      麻醉科: 0,
      臨床腫瘤科: 0,
      眼科: 1,
      耳鼻喉科: 0,
      神經外科: 0,
      精神科: 0,
      骨科: 0,
      紓緩醫學科: 0,
      婦科: 0,
      產科: 0,
      兒科: 0,
      牙科: 0,
    },
  },
  {
    name: "屯門醫院",
    type: "新界西醫院聯網",
    contact: "2468 5111",
    website:
      "https://www.ha.org.hk/visitor/ha_visitor_index.asp?Content_ID=100173&Lang=CHIB5",
    address: "新界屯門青松觀路廿三號",
    specialistServices: {
      內科: 1,
      外科: 1,
      心胸外科: 1,
      麻醉科: 0,
      臨床腫瘤科: 1,
      眼科: 0,
      耳鼻喉科: 1,
      神經外科: 1,
      精神科: 1,
      骨科: 1,
      紓緩醫學科: 0,
      婦科: 1,
      產科: 1,
      兒科: 1,
      牙科: 0,
    },
  },
  {
    name: "大口環根德公爵夫人兒童醫院",
    type: "港島西醫院聯網",
    contact: "2817 7111",
    website:
      "https://www.ha.org.hk/visitor/ha_visitor_index.asp?Content_ID=100137&Lang=CHIB5",
    address: "香港薄扶林大口環道12號",
    specialistServices: {
      內科: 1,
      外科: 0,
      心胸外科: 0,
      麻醉科: 0,
      臨床腫瘤科: 0,
      眼科: 0,
      耳鼻喉科: 0,
      神經外科: 0,
      精神科: 0,
      骨科: 1,
      紓緩醫學科: 1,
      婦科: 0,
      產科: 0,
      兒科: 1,
      牙科: 0,
    },
  },
  {
    name: "贊育醫院",
    type: "港島西醫院聯網",
    contact: "2589 2100",
    website:
      "https://www.ha.org.hk/visitor/ha_visitor_index.asp?Content_ID=100133&Lang=CHIB5",
    address: "香港西營盤醫院道30號",
    specialistServices: {
      內科: 1,
      外科: 0,
      心胸外科: 0,
      麻醉科: 0,
      臨床腫瘤科: 0,
      眼科: 0,
      耳鼻喉科: 0,
      神經外科: 0,
      精神科: 1,
      骨科: 0,
      紓緩醫學科: 1,
      婦科: 1,
      產科: 1,
      兒科: 0,
      牙科: 0,
    },
  },
  {
    name: "天水圍醫院",
    type: "新界西醫院聯網",
    contact: "3513 5000",
    website:
      "https://www.ha.org.hk/visitor/ha_visitor_index.asp?Content_ID=235909&Lang=CHIB5",
    address: "新界天水圍天壇街11號",
    specialistServices: {
      內科: 1,
      外科: 0,
      心胸外科: 0,
      麻醉科: 1,
      臨床腫瘤科: 0,
      眼科: 0,
      耳鼻喉科: 0,
      神經外科: 0,
      精神科: 0,
      骨科: 1,
      紓緩醫學科: 1,
      婦科: 0,
      產科: 0,
      兒科: 0,
      牙科: 0,
    },
  },
  {
    name: "伊利沙伯醫院",
    type: "九龍中醫院聯網",
    contact: "3506 8888",
    website:
      "https://www.ha.org.hk/visitor/ha_visitor_index.asp?Content_ID=100149&Lang=CHIB5",
    address: "九龍加士居道30號",
    specialistServices: {
      內科: 1,
      外科: 1,
      心胸外科: 1,
      麻醉科: 1,
      臨床腫瘤科: 1,
      眼科: 0,
      耳鼻喉科: 1,
      神經外科: 1,
      精神科: 1,
      骨科: 1,
      紓緩醫學科: 0,
      婦科: 1,
      產科: 1,
      兒科: 1,
      牙科: 0,
    },
  },
  {
    name: "瑪麗醫院",
    type: "港島西醫院聯網",
    contact: "2255 3838",
    website:
      "https://www.ha.org.hk/visitor/ha_visitor_index.asp?Content_ID=100131&Lang=CHIB5",
    address: "香港薄扶林道102號",
    specialistServices: {
      內科: 1,
      外科: 1,
      心胸外科: 1,
      麻醉科: 1,
      臨床腫瘤科: 1,
      眼科: 0,
      耳鼻喉科: 1,
      神經外科: 1,
      精神科: 1,
      骨科: 1,
      紓緩醫學科: 0,
      婦科: 1,
      產科: 1,
      兒科: 1,
      牙科: 0,
    },
  },
  {
    name: "律敦治醫院",
    type: "港島東醫院聯網",
    contact: "2291 2000",
    website:
      "https://www.ha.org.hk/visitor/ha_visitor_index.asp?Content_ID=100144&Lang=CHIB5",
    address: "香港灣仔皇后大道東266號",
    specialistServices: {
      內科: 1,
      外科: 1,
      心胸外科: 0,
      麻醉科: 0,
      臨床腫瘤科: 0,
      眼科: 0,
      耳鼻喉科: 1,
      神經外科: 0,
      精神科: 0,
      骨科: 1,
      紓緩醫學科: 1,
      婦科: 0,
      產科: 0,
      兒科: 0,
      牙科: 0,
    },
  },
  {
    name: "威爾斯親王醫院",
    type: "新界東醫院聯網",
    contact: "3505 2211",
    website:
      "https://www.ha.org.hk/visitor/ha_visitor_index.asp?Content_ID=100166&Lang=CHIB5",
    address: "新界沙田銀城街30-32號",
    specialistServices: {
      內科: 1,
      外科: 1,
      心胸外科: 0,
      麻醉科: 0,
      臨床腫瘤科: 1,
      眼科: 1,
      耳鼻喉科: 1,
      神經外科: 1,
      精神科: 1,
      骨科: 1,
      紓緩醫學科: 1,
      婦科: 1,
      產科: 1,
      兒科: 1,
      牙科: 0,
    },
  },
  {
    name: "北大嶼山醫院",
    type: "九龍西醫院聯網",
    contact: "3467 7000",
    website:
      "https://www.ha.org.hk/visitor/ha_visitor_index.asp?Content_ID=216546&Lang=CHIB5",
    address: "大嶼山東涌松仁路8號",
    specialistServices: {
      內科: 1,
      外科: 1,
      心胸外科: 0,
      麻醉科: 0,
      臨床腫瘤科: 0,
      眼科: 0,
      耳鼻喉科: 0,
      神經外科: 0,
      精神科: 1,
      骨科: 1,
      紓緩醫學科: 0,
      婦科: 1,
      產科: 0,
      兒科: 1,
      牙科: 0,
    },
  },
  {
    name: "聖母醫院",
    type: "九龍中醫院聯網",
    contact: "2320 2121",
    website:
      "https://www.ha.org.hk/visitor/ha_visitor_index.asp?Content_ID=100155&Lang=CHIB5",
    address: "九龍黃大仙沙田坳道118號",
    specialistServices: {
      內科: 1,
      外科: 1,
      心胸外科: 0,
      麻醉科: 0,
      臨床腫瘤科: 0,
      眼科: 0,
      耳鼻喉科: 1,
      神經外科: 0,
      精神科: 0,
      骨科: 1,
      紓緩醫學科: 0,
      婦科: 1,
      產科: 0,
      兒科: 1,
      牙科: 0,
    },
  },
  {
    name: "東區尤德夫人那打素醫院",
    type: "港島東醫院聯網",
    contact: "2595 6111",
    website:
      "https://www.ha.org.hk/visitor/ha_visitor_index.asp?Content_ID=100141&Lang=CHIB5",
    address: "香港柴灣樂民道3號",
    specialistServices: {
      內科: 1,
      外科: 1,
      心胸外科: 0,
      麻醉科: 1,
      臨床腫瘤科: 1,
      眼科: 1,
      耳鼻喉科: 1,
      神經外科: 1,
      精神科: 1,
      骨科: 1,
      紓緩醫學科: 0,
      婦科: 1,
      產科: 1,
      兒科: 1,
      牙科: 0,
    },
  },
  {
    name: "博愛醫院",
    type: "新界西醫院聯網",
    contact: "2486 8000",
    website:
      "https://www.ha.org.hk/visitor/ha_visitor_index.asp?Content_ID=100174&Lang=CHIB5",
    address: "新界元朗坳頭",
    specialistServices: {
      內科: 1,
      外科: 1,
      心胸外科: 0,
      麻醉科: 0,
      臨床腫瘤科: 0,
      眼科: 1,
      耳鼻喉科: 1,
      神經外科: 0,
      精神科: 0,
      骨科: 1,
      紓緩醫學科: 0,
      婦科: 0,
      產科: 0,
      兒科: 0,
      牙科: 0,
    },
  },
  {
    name: "廣華醫院",
    type: "九龍中醫院聯網",
    contact: "2332 2311",
    website:
      "https://www.ha.org.hk/visitor/ha_visitor_index.asp?Content_ID=100153&Lang=CHIB5",
    address: "九龍窩打老道25號",
    specialistServices: {
      內科: 1,
      外科: 1,
      心胸外科: 0,
      麻醉科: 1,
      臨床腫瘤科: 0,
      眼科: 0,
      耳鼻喉科: 1,
      神經外科: 1,
      精神科: 1,
      骨科: 1,
      紓緩醫學科: 0,
      婦科: 1,
      產科: 1,
      兒科: 1,
      牙科: 0,
    },
  },
  {
    name: "香港佛教醫院",
    type: "九龍中醫院聯網",
    contact: "2339 6111",
    website:
      "https://www.ha.org.hk/visitor/ha_visitor_index.asp?Content_ID=100152&Lang=CHIB5",
    address: "九龍樂富杏林街10號",
    specialistServices: {
      內科: 1,
      外科: 0,
      心胸外科: 0,
      麻醉科: 0,
      臨床腫瘤科: 0,
      眼科: 0,
      耳鼻喉科: 0,
      神經外科: 0,
      精神科: 0,
      骨科: 0,
      紓緩醫學科: 0,
      婦科: 0,
      產科: 0,
      兒科: 0,
      牙科: 0,
    },
  },
  {
    name: "青山醫院",
    type: "新界西醫院聯網",
    contact: "2456 7111",
    website:
      "https://www.ha.org.hk/visitor/ha_visitor_index.asp?Content_ID=100176&Lang=CHIB5",
    address: "新界屯門青松觀路15號",
    specialistServices: {
      內科: 0,
      外科: 0,
      心胸外科: 0,
      麻醉科: 0,
      臨床腫瘤科: 0,
      眼科: 0,
      耳鼻喉科: 0,
      神經外科: 0,
      精神科: 0,
      骨科: 0,
      紓緩醫學科: 0,
      婦科: 0,
      產科: 0,
      兒科: 0,
      牙科: 0,
    },
  },
  {
    name: "沙田慈氏護養院",
    type: "新界東醫院聯網",
    contact: "2636 7288",
    website:
      "https://www.ha.org.hk/visitor/ha_visitor_index.asp?Content_ID=100169&Lang=CHIB5",
    address: "新界沙田亞公角山路30號",
    specialistServices: {
      內科: 0,
      外科: 0,
      心胸外科: 0,
      麻醉科: 0,
      臨床腫瘤科: 0,
      眼科: 0,
      耳鼻喉科: 0,
      神經外科: 0,
      精神科: 0,
      骨科: 0,
      紓緩醫學科: 0,
      婦科: 0,
      產科: 0,
      兒科: 0,
      牙科: 0,
    },
  },
  {
    name: "明愛醫院",
    type: "九龍西醫院聯網",
    contact: "3408 5678",
    website:
      "https://www.ha.org.hk/visitor/ha_visitor_index.asp?Content_ID=100163&Lang=CHIB5",
    address: "九龍深水埗永康街111號",
    specialistServices: {
      內科: 1,
      外科: 1,
      心胸外科: 0,
      麻醉科: 1,
      臨床腫瘤科: 0,
      眼科: 1,
      耳鼻喉科: 1,
      神經外科: 0,
      精神科: 1,
      骨科: 1,
      紓緩醫學科: 0,
      婦科: 1,
      產科: 0,
      兒科: 1,
      牙科: 1,
    },
  },
  {
    name: "雅麗氏何妙齡那打素醫院",
    type: "新界東醫院聯網",
    contact: "2689 2000",
    website:
      "https://www.ha.org.hk/visitor/ha_visitor_index.asp?Content_ID=100171&Lang=CHIB5",
    address: "新界大埔全安路11號",
    specialistServices: {
      內科: 1,
      外科: 1,
      心胸外科: 0,
      麻醉科: 1,
      臨床腫瘤科: 0,
      眼科: 1,
      耳鼻喉科: 1,
      神經外科: 0,
      精神科: 1,
      骨科: 1,
      紓緩醫學科: 0,
      婦科: 1,
      產科: 0,
      兒科: 1,
      牙科: 0,
    },
  },
  {
    name: "葛量洪醫院",
    type: "港島西醫院聯網",
    contact: "2518 2111",
    website:
      "https://www.ha.org.hk/visitor/ha_visitor_index.asp?Content_ID=100139",
    address: "香港仔黃竹坑道125號",
    specialistServices: {
      內科: 0,
      外科: 0,
      心胸外科: 0,
      麻醉科: 0,
      臨床腫瘤科: 0,
      眼科: 1,
      耳鼻喉科: 0,
      神經外科: 0,
      精神科: 0,
      骨科: 0,
      紓緩醫學科: 1,
      婦科: 0,
      產科: 0,
      兒科: 0,
      牙科: 0,
    },
  },
];
